CRISP - DM 

Busines understanding

data forms different
99% - not enough data


In [6]:
!pip install numpy

In [7]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in c:\users\deepesh\anaconda2\lib\site-packages


In [8]:
import numpy as np

In [9]:
np.array([1,2,3])

array([1, 2, 3])

In [10]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [12]:
np.ones((3,2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
#array of even spaced number
np.linspace(0,1,4)

array([ 0.        ,  0.33333333,  0.66666667,  1.        ])

In [15]:
mean = 10
stdev = 3
number_values = 20
np.random.normal(mean,stdev,number_values)

array([  7.1945989 ,   8.50866626,  10.63789035,   9.22336137,
         9.40744909,   6.59240074,   4.32498744,  15.06725718,
         8.08076555,  14.63008286,  14.59878429,   8.13436985,
        11.98872534,   9.74521279,  10.60068696,   7.88307641,
        16.41111266,  12.27876695,   6.87443426,  12.34225337])

In [16]:
#array math
x=[1,2,3,4]
print (x+10)

TypeError: can only concatenate list (not "int") to list

In [ ]:
x = np.array(x)
print (x+10)

In [ ]:
#it will make everything object unless specify.
y = np.array([1,2,3,'4'])
print (y)

In [ ]:
x = np.arange(4)
print (x[0])
print (x[1])

In [ ]:
print x

In [ ]:
x[-4]

In [ ]:
x[-5]

In [ ]:
#reshape
x = np.arange(6)
print x

In [ ]:
x.reshape(2,3)

In [ ]:
x.reshape(5,1)

In [ ]:
x.reshape(6,1)

In [ ]:
x.reshape(1,6)

In [ ]:
print (x[-1])

In [ ]:
print (x[-1,-1])

In [ ]:
x = np.arange(10)
print (x)
print (x[:3:])
print(x[1:4])
print(x[-3:])

learning
deployment
mastering

10000 hrs..outliers by malcolm, cal newport

super intelligence
mastering algorithm


In [ ]:
print (x[::-1])

In [ ]:
print (x[::2])

In [ ]:
print (x[::3])

In [ ]:
x = np.arange(25).reshape(5,5)
print x

In [ ]:
print (x[:4,:4])

In [ ]:
print (x[::2,::2])

In [ ]:
x = np.random.randint(0,9,6)

In [ ]:
print x

In [ ]:
indice = [0,-2,-2]
print (x[indice])
print x + 10 

In [ ]:
arrayLength = 5
x1 = np.arange(arrayLength)
#x2 = np.arange(arrayLength)
x2 = x1
print (x1)

In [ ]:
print (x2) * -1

In [ ]:
ran_numb = np.random.permutation(arrayLength)

In [ ]:
print ran_numb

In [ ]:
print x1[ran_numb]

In [ ]:
print x2[ran_numb]

In [ ]:
# boolean values
x = np.arange(5)

In [ ]:
print (x)

In [ ]:
print x > 2

In [ ]:
print x[x>2]

In [ ]:
print(x[np.array([False,True,False,True,True])])

In [ ]:
x=np.arange(16).reshape(2,2,2,2)
print (x)

In [ ]:
print x[0]

In [ ]:
print x[0,0]

In [ ]:
print x[0,0,0]

In [ ]:
print x[0,1,1,1]

In [ ]:
y = np.arange(9).reshape(3,3)

In [ ]:
print y

In [ ]:
y.ravel()

In [ ]:
x.ravel()

In [ ]:
x=np.arange(27)

In [ ]:
x

In [ ]:
x_reverse = x[::-1]

In [ ]:
x_reverse

In [ ]:
x_3d = x.reshape(3,3,3)

In [ ]:
print x_3d

In [ ]:
#child = np.array([0,2,3,4,2,2,2,2])
child = np.array([0,1,2,2,5])
house_sum = sum(child)
print "the mean of child", house_sum / 5

In [ ]:
print " the mean ", np.mean(child)

median is less suscept to outliers

In [ ]:
bill = 10000
ted = 24640
cyrus = 30000
john = 25000
matt = 20000

income = (bill,ted,cyrus,john,matt)
sorted (income)
np.median(income)

In [ ]:
np.mean(income)

In [ ]:
trump = 10000000000
income = np.append(income,trump)

In [ ]:
np.median(income)
income

In [ ]:
np.median(income)

In [ ]:
np.mean(income)

In [ ]:
fake_income = np.random.normal(24000,15000,10000)
np.mean(fake_income)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.hist(fake_income,10)
plt.show()

in normal distribution mean is median


In [ ]:
np.median(fake_income)

In [ ]:
fake_income = np.append(fake_income, trump)

In [ ]:
fake_income

In [ ]:
np.median(fake_income)

In [ ]:
np.mean(fake_income)

In [ ]:
ages = np.random.randint(2,high=18,size=20)
ages

In [ ]:
from scipy import stats
stats.mode(ages)

mode is more used for categorical validation


In [ ]:
variance = stats.variation(ages)

In [ ]:
import math as m

In [ ]:
m.sqrt(variance)

In [ ]:
std = variance ** 0.5
print 'stand dev is', std

In [ ]:
d=np.array([1,4,5,4,8])
np.std(d)
plt.hist(d,50)
plt.show()
print np.std(d)

# Pandas
create a data frame
importing and exprting file types:  CSV, XML,XLSX, JSON
Connect to SQL database and fire a query
Exploring Titanic dataset

Data frame syntax

pd.DataFrame (column: values in column)

In [ ]:
import pandas as pd

In [ ]:
df  = pd.DataFrame({'name':['Bob', 'Jen', 'Tim'],
                   'age':[20,30,40],
                   'pet':['cat','dog','bird']})
print df

In [ ]:
print df

In [ ]:
df

In [ ]:
#print df.columns
df.columns

In [ ]:
print df.index

In [ ]:
df.sort

In [ ]:
df

In [ ]:
df.sort.value

In [ ]:
df['name']

In [ ]:
df.name

In [ ]:
df[['name','pet']]

In [ ]:
# indexing
df.ix[0]

In [ ]:
df.ix[1]

http://pandas.pydata.or/pandas-docs/stable/generated/pandas.DataFrame.ix.html

In [ ]:
# row index stays with data
df.sort_values('pet',inplace=True)
df

df.iloc[0]

In [ ]:
df.iloc[0]

In [ ]:
df.ix[0]

In [ ]:
# select all rows of a col
df.iloc[:,2]

In [ ]:
df.iloc[-1:,]

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('filesday2/test_pandas.csv')
data

In [25]:
arraylength = 27
x = np.arange(arraylength)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [27]:
x_reverse = x[::-1]
x_reverse

array([26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,
        9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
data.to_csv('filesday2/test_pandas_no_header.csv',header=False,index=True)

In [ ]:
data_no_header = pd.read_csv('filesday2/test_pandas_no_header.csv')
data_no_header

In [ ]:
data_no_header = pd.read_csv('filesday2/test_pandas_no_header.csv',header=None)
data_no_header

In [ ]:
data_no_header = pd.read_csv('filesday2/test_pandas_no_header.csv',header='infer')
data_no_header

In [18]:
data = pd.read_excel('filesday2/test_pandas.xlsm','Sheet1')
data

Column A Column B  Column C
0         1      cat       1.1
1         2      dog       2.2
2         3     bird       3.3

In [19]:
writer = pd.ExcelWriter('filesday2/test_sheets.xlsx')
data.to_excel(writer,'Original')
data.to_excel(writer,'Copy')
writer.save()

In [21]:
import sqlite3

In [23]:
conn = sqlite3.connect('filesday2/test_pandas.db')

In [24]:
sql_query ="SELECT * FROM test"
data = pd.read_sql(sql_query,conn)
data

id           city    mascot
0   1  San Francisco     49ers
1   2        Oakland   Raiders
2   3        Seattle  Seahawks
3   4        Chicago     Bears
4   5            NYC      Jets

In [30]:
sql_query = "select city from test"
data = pd.read_sql(sql_query,conn)
data

city
0  San Francisco
1        Oakland
2        Seattle
3        Chicago
4            NYC

In [34]:
new_data = pd.DataFrame({'id':[4,5],'city':['Chicago','NYC'],'mascot':['Bears','Jets']})
new_data = new_data[['id','city','mascot']]
new_data

id     city mascot
0   4  Chicago  Bears
1   5      NYC   Jets

In [36]:
new_data.to_sql('filesday2/test3',conn,if_exists='append',index=False)

In [37]:
new_data.to_sql('filesday2/newtest',conn)

In [38]:
new_data.to_sql('filesday2/test',conn,if_exists='append',index=False)

In [39]:

conn.close()

In [42]:
#load and investigate the file
import pandas as pd
data = pd.read_csv('filesday2/train.csv')

In [43]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [44]:
data.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 66.2+ KB


In [46]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [47]:
#filter data
data[data.Sex=='male']

PassengerId  Survived  Pclass                                     Name  \
0              1         0       3                  Braund, Mr. Owen Harris   
4              5         0       3                 Allen, Mr. William Henry   
5              6         0       3                         Moran, Mr. James   
6              7         0       1                  McCarthy, Mr. Timothy J   
7              8         0       3           Palsson, Master. Gosta Leonard   
12            13         0       3           Saundercock, Mr. William Henry   
13            14         0       3              Andersson, Mr. Anders Johan   
16            17         0       3                     Rice, Master. Eugene   
17            18         1       2             Williams, Mr. Charles Eugene   
20            21         0       2                     Fynney, Mr. Joseph J   
21            22         1       2                    Beesley, Mr. Lawrence   
23            24         1       1             Sloper, Mr. William Thompson   
26            27         0       3                  Emir, Mr. Farred Chehab   
27            28         0       1           Fortune, Mr. Charles Alexander   
29            30         0       3                      Todoroff, Mr. Lalio   
30            31         0       1                 Uruchurtu, Don. Manuel E   
33            34         0       2                    Wheadon, Mr. Edward H   
34            35         0       1                  Meyer, Mr. Edgar Joseph   
35            36         0       1           Holverson, Mr. Alexander Oskar   
36            37         1       3                         Mamee, Mr. Hanna   
37            38         0       3                 Cann, Mr. Ernest Charles   
42            43         0       3                      Kraeff, Mr. Theodor   
45            46         0       3                 Rogers, Mr. William John   
46            47         0       3                        Lennon, Mr. Denis   
48            49         0       3                      Samaan, Mr. Youssef   
50            51         0       3               Panula, Master. Juha Niilo   
51            52         0       3             Nosworthy, Mr. Richard Cater   
54            55         0       1           Ostby, Mr. Engelhart Cornelius   
55            56         1       1                        Woolner, Mr. Hugh   
57            58         0       3                      Novel, Mr. Mansouer   
..           ...       ...     ...                                      ...   
840          841         0       3              Alhomaki, Mr. Ilmari Rudolf   
841          842         0       2                 Mudd, Mr. Thomas Charles   
843          844         0       3               Lemberopolous, Mr. Peter L   
844          845         0       3                      Culumovic, Mr. Jeso   
845          846         0       3                      Abbing, Mr. Anthony   
846          847         0       3                 Sage, Mr. Douglas Bullen   
847          848         0       3                       Markoff, Mr. Marin   
848          849         0       2                        Harper, Rev. John   
850          851         0       3  Andersson, Master. Sigvard Harald Elias   
851          852         0       3                      Svensson, Mr. Johan   
857          858         1       1                   Daly, Mr. Peter Denis    
859          860         0       3                         Razi, Mr. Raihed   
860          861         0       3                  Hansen, Mr. Claus Peter   
861          862         0       2              Giles, Mr. Frederick Edward   
864          865         0       2                   Gill, Mr. John William   
867          868         0       1     Roebling, Mr. Washington Augustus II   
868          869         0       3              van Melkebeke, Mr. Philemon   
869          870         1       3          Johnson, Master. Harold Theodor   
870          871         0       3                     

In [50]:
data[Sex=='male']

NameError: name 'Sex' is not defined

In [51]:
data.Age[data.Sex== 'male']

0      22.0
4      35.0
5       NaN
6      54.0
7       2.0
12     20.0
13     39.0
16      2.0
17      NaN
20     35.0
21     34.0
23     28.0
26      NaN
27     19.0
29      NaN
30     40.0
33     66.0
34     28.0
35     42.0
36      NaN
37     21.0
42      NaN
45      NaN
46      NaN
48      NaN
50      7.0
51     21.0
54     65.0
55      NaN
57     28.5
       ... 
840    20.0
841    16.0
843    34.5
844    17.0
845    42.0
846     NaN
847    35.0
848    28.0
850     4.0
851    74.0
857    51.0
859     NaN
860    41.0
861    21.0
864    24.0
867    31.0
868     NaN
869     4.0
870    26.0
872    33.0
873    47.0
876    20.0
877    19.0
878     NaN
881    33.0
883    28.0
884    25.0
886    27.0
889    26.0
890    32.0
Name: Age, dtype: float64

In [52]:
print data.Sex[data.Sex=='male'].count()
print data.Sex[data.Sex=='female'].count()

577
314


In [53]:
#survival rate for men age > = 18

In [55]:
data.Survived[(data.Sex=='male') & (data.Age>=18)].mean()

0.17721518987341772

In [56]:
data.Survived[(data.Sex=='female') & (data.Age<18)].mean()

0.6909090909090909

In [57]:
#survival rates by sex
data.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [58]:
new=data.groupby('Sex')[['Survived','Age']].mean()

In [59]:
new.index

Index([u'female', u'male'], dtype='object', name=u'Sex')

In [60]:
new

Survived        Age
Sex                        
female  0.742038  27.915709
male    0.188908  30.726645

In [61]:
new.reset_index(inplace=True)

In [62]:
print(new.index)

RangeIndex(start=0, stop=2, step=1)


In [63]:
print new

      Sex  Survived        Age
0  female  0.742038  27.915709
1    male  0.188908  30.726645


In [64]:
new.index

RangeIndex(start=0, stop=2, step=1)

In [65]:
new

Sex  Survived        Age
0  female  0.742038  27.915709
1    male  0.188908  30.726645